import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { build } from 'esbuild';
const compiled = await build({entryPoints:['src/progress.ts'],bundle:true,platform:'node',format:'cjs',write:false});
const module = {exports:{}};
vm.runInNewContext(compiled.outputFiles[0].text,{module,exports:module.exports});
const {toSpeechText,interpretSdkEvent,replyForSpeech,immediateAck}=module.exports;
assert.equal(immediateAck('任意问题'), '好的，收到。我现在开始处理，完成后告诉你结果。');
assert.equal(replyForSpeech('## 结论\n\n修改已完成。\n\n### 代码\n\n```js\nconst x = 1;\n```'), '修改已完成。');
assert.match(replyForSpeech('修改已完成。\n\n验证未通过，还不能上线。'), /未通过/);
assert.equal(toSpeechText('请参考[说明](https://example.com)。'), '请参考说明。');
assert.ok(toSpeechText('很长的内容'.repeat(100)).length <= 180);
assert.equal(toSpeechText('已完成。\n```sh\nnpm test\n```\n`git status`'), '已完成。');
assert.equal(toSpeechText('说明。\n~~~js\nsecret()'), '说明。');
assert.equal(interpretSdkEvent({type:'tool_call',name:'Shell',status:'running',args:{command:'npm test'}}).speak,false);
assert.ok(!interpretSdkEvent({type:'tool_call',name:'Shell',status:'error',args:{command:'npm test'}}).speakText.includes('npm'));
const timers=[];const utterances=[];
const window={speechSynthesis:{getVoices:()=>[],addEventListener(){},speak(u){utterances.push(u)},cancel(){}}};
vm.runInNewContext(readFileSync('media/voice.js','utf8'),{window,navigator:{userActivation:{hasBeenActive:true}},SpeechSynthesisUtterance:class{constructor(text){this.text=text}},setTimeout(fn){timers.push(fn)}});
const speaker=window.Voice.createSpeaker();
speaker.speak('第一条。');const old=utterances[0];
speaker.speak('第二条。');speaker.cancel();
for(const fn of timers.splice(0))fn();
assert.equal(utterances.length,1,'cancel must invalidate delayed replacement');
speaker.speak('最新内容。');old.onend();
assert.equal(speaker.currentUtter.text,'最新内容。','stale callbacks must not clear new audio');
const html=readFileSync('media/mic.html','utf8');
new vm.Script(html.match(/<script>([\s\S]*?)<\/script>/)[1]);
console.log('PASS: speech filtering, silent tool progress, delayed playback cancellation, stale callbacks, browser syntax');
